# -*- coding: utf-8 -*-
"""fix_fastq_split_compress.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/124FB1hoP7ipO6aHEpBcC4P0lv1ssbDp6
"""

import os
import gzip
from pathlib import Path
import subprocess

fastq_dir = Path("/fastq_downloads")
log_processed = fastq_dir / "fix_processed.log"
log_skipped = fastq_dir / "fix_skipped.log"

def is_already_processed(accession):
    return (fastq_dir / f"{accession}_1.fastq.gz").exists() and (fastq_dir / f"{accession}_2.fastq.gz").exists()

def split_fastq(filename):
    acc = filename.stem
    read1_file = fastq_dir / f"{acc}_1.fastq"
    read2_file = fastq_dir / f"{acc}_2.fastq"

    with open(filename, 'r') as infile, \
         open(read1_file, 'w') as out1, \
         open(read2_file, 'w') as out2:

        while True:
            header = infile.readline()
            if not header:
                break
            seq = infile.readline()
            plus = infile.readline()
            qual = infile.readline()

            if header.startswith('@') and '/1' in header:
                out1.write(f"{header}{seq}{plus}{qual}")
            elif header.startswith('@') and '/2' in header:
                out2.write(f"{header}{seq}{plus}{qual}")
            else:
                # fallback: assume alternating reads
                out1.write(f"{header}{seq}{plus}{qual}")
                header = infile.readline()
                if not header:
                    break
                seq = infile.readline()
                plus = infile.readline()
                qual = infile.readline()
                out2.write(f"{header}{seq}{plus}{qual}")
                continue

    return read1_file, read2_file

def compress_file(file_path):
    subprocess.run(["gzip", str(file_path)], check=True)

with open(log_processed, 'a') as log_ok, open(log_skipped, 'a') as log_skip:
    for fastq_file in fastq_dir.glob("*.fastq"):
        acc = fastq_file.stem
        if is_already_processed(acc):
            print(f"[SKIP] {acc} already processed.")
            log_skip.write(f"{acc} skipped\n")
            continue
        print(f"[PROCESSING] {acc}")
        try:
            read1, read2 = split_fastq(fastq_file)
            compress_file(read1)
            compress_file(read2)
            fastq_file.unlink()  # delete the original file
            log_ok.write(f"{acc} split and compressed\n")
            print(f"[DONE] {acc} split & compressed.")
        except Exception as e:
            print(f"[ERROR] Failed to process {acc}: {e}")