# -*- coding: utf-8 -*-
"""script_updated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ep1OhAQd4rIuqpb30g2H7Trgs7DSVG5S
"""

import os
import pandas as pd
import subprocess
from pathlib import Path

# Load spreadsheet
excel_path = "M. africanum raw main.xlsx"
df = pd.read_excel(excel_path)

# Define folders
sra_cache = Path("sra_cache")
fastq_folder = Path("fastq_downloads")
sra_cache.mkdir(exist_ok=True)
fastq_folder.mkdir(exist_ok=True)

# Extract accession numbers
accessions = df["Run_AC_NUMBER"].dropna().unique()

# Log files
log_success = fastq_folder / "download_success.log"
log_failed = fastq_folder / "download_failed.log"
with open(log_success, 'a') as success_log, open(log_failed, 'a') as failed_log:
    success_log.write("\n--- Successful Downloads ---\n")
    failed_log.write("\n--- Failed Downloads ---\n")

    for acc in accessions:
        fastq1 = fastq_folder / f"{acc}_1.fastq.gz"
        fastq2 = fastq_folder / f"{acc}_2.fastq.gz"

        # Skip if both paired files exist and pass gzip integrity
        if fastq1.exists() and fastq2.exists():
            try:
                subprocess.run(["gunzip", "-t", str(fastq1)], check=True)
                subprocess.run(["gunzip", "-t", str(fastq2)], check=True)
                print(f"[SKIP] {acc} already exists and passed integrity check.")
                continue
            except subprocess.CalledProcessError:
                print(f"[WARNING] {acc} files exist but failed integrity. Redownloading...")

        try:
            print(f"[INFO] Downloading {acc}...")
            # Step 1: Prefetch to SRA cache
            subprocess.run(["prefetch", acc, "-O", str(sra_cache)], check=True)

            # Step 2: Dump to fastq with threads and gzip compression
            subprocess.run([
                "fasterq-dump", acc,
                "--threads", "4",
                "--outdir", str(fastq_folder),
                "--temp", str(sra_cache)
            ], check=True)

            # Step 3: Gzip the outputs
            for suffix in ["_1.fastq", "_2.fastq"]:
                raw_file = fastq_folder / f"{acc}{suffix}"
                if raw_file.exists():
                    subprocess.run(["gzip", str(raw_file)], check=True)

            print(f"[SUCCESS] {acc} downloaded and compressed.")
            success_log.write(f"{acc}\n")

        except subprocess.CalledProcessError:
            print(f"[FAILED] {acc} failed to download or process.")
            failed_log.write(f"{acc}\n")

print("\nAll downloads completed.")